package vista;

/**
 *
 * @author Agarimo
 */
public class Insercion extends javax.swing.JFrame {

    /**
     * Creates new form Insercion
     */
    public Insercion() {
        initComponents();
    }
    
    public void setProgreso(int value){
        progreso.setValue(value);
    }
    
    public void setProgresoBB0(int value){
        progresoBB0.setValue(value);
    }
    
    public void setLabel(String texto){
        label.setText(texto);
    }
    
    public void setTitulo(String titulo){
        this.setTitle(titulo);
    }
    
    public void setIndeterminado(boolean aux){
        progreso.setIndeterminate(aux);
        progresoBB0.setVisible(!aux);
    }
    
    public void setFin(){
        progreso.setIndeterminate(false);
        progreso.setValue(100);
        progreso.setEnabled(false);
        label.setText("Tarea completada");
        this.setTitle("Finalizado");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        webPanel1 = new com.alee.laf.panel.WebPanel();
        label = new com.alee.laf.label.WebLabel();
        progreso = new com.alee.laf.progressbar.WebProgressBar();
        progresoBB0 = new com.alee.laf.progressbar.WebProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        webPanel1.add(label, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(webPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(progreso, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(progresoBB0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(progreso, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(progresoBB0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(webPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.alee.laf.label.WebLabel label;
    private com.alee.laf.progressbar.WebProgressBar progreso;
    private com.alee.laf.progressbar.WebProgressBar progresoBB0;
    private com.alee.laf.panel.WebPanel webPanel1;
    // End of variables declaration//GEN-END:variables
}
